version: '3.8'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/scraped_db
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
